### ISSUE TITLE
Desktop file does not pass desktop-file-validate

### ISSUE THREAD

**Issue by probonopd** [breeze2/breader#53]
References:
* http://manpages.ubuntu.com/manpages/bionic/man1/desktop-file-validate.1.html
* https://github.com/AppImage/appimage.github.io/pull/1765

**Comment by breeze2** [comment]
Thanks for your feedback! I will fix it soon.

**Comment by breeze2** [comment]
> References:
> 
> * http://manpages.ubuntu.com/manpages/bionic/man1/desktop-file-validate.1.html
> * [AppImage/appimage.github.io#1765](https://github.com/AppImage/appimage.github.io/pull/1765)

Very sorry, I reply late. The [Breader-2.1.1.AppImage](https://github.com/breeze2/breader/releases/download/v2.1.1/Breader-2.1.1.AppImage) passed the validation of desktop-file-validate.

![4C98D7FE-BA21-4294-9B19-B28E559D4D1C](https://user-images.githubusercontent.com/5266711/66794292-8679a380-ef33-11e9-9bb8-c64186bbc7fa.png)
